def afficher_menu():
    print("\n========================")
    print("1. Ajouter un dataset")
    print("2. Afficher les datasets")
    print("3. Rechercher")
    print("4. Quitter")
    print("5. Trier")
    print("6. Modifier")
    print("7. Supprimer")
    print("8. Statistiques")
    print("9. Sauvegarder (CSV)")
    print("10. Recharger (CSV)")
    print("11. Sauvegarder (JSON)")
    print("12. Recharger (JSON)")
    print("==================")
